/*
 * Copyright (C) 2026  Gabriel Fontán (BobbyESP)
 */
package com.bobbyesp.docucraft.core.presentation.theme

import android.content.Context
import android.util.Log
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.MaterialExpressiveTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.MotionScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFontFamilyResolver
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.createFontFamilyResolver
import com.bobbyesp.docucraft.core.domain.model.PaletteStyleConfig
import com.bobbyesp.docucraft.core.domain.model.UserPreferences
import com.materialkolor.blend.Blend
import com.materialkolor.dynamicColorScheme
import com.materialkolor.dynamiccolor.ColorSpec
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** The type roles Material's [androidx.compose.material3.Typography] has no slot for. */
@Immutable data class DocucraftTypography(val monospace: FontFamily = FontFamily.Monospace)

private val LocalDocucraftTypography = staticCompositionLocalOf { DocucraftTypography() }

/** The app's additions to [androidx.compose.material3.MaterialTheme], read the same way. */
object DocucraftTheme {
    val typography: DocucraftTypography
        @Composable @ReadOnlyComposable get() = LocalDocucraftTypography.current
}

/**
 * The app's theme: Material 3 Expressive, with colors from the wallpaper or generated by
 * MaterialKolor from the user's seed color. A change moves every color of the app to its new one
 * (see [rememberThemeTransition]).
 *
 * @param isDark whether to use the dark scheme; taken from [userPreferences] unless the caller has
 *   already worked it out.
 */
@Suppress("ModifierRequired")
@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun DocucraftTheme(
    userPreferences: UserPreferences = UserPreferences(),
    isDark: Boolean = userPreferences.themeConfig.isDarkTheme(),
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current
    val motionScheme = MotionScheme.expressive()

    val cache = remember(context) { ColorSchemeCache() }
    val built =
        rememberColorScheme(
            source =
                ColorSchemeSource(
                    isDark = isDark,
                    useWallpaperColors = userPreferences.useDynamicColoring,
                    seedColor = userPreferences.themeSeedColor,
                    paletteStyle = userPreferences.paletteStyle,
                    pureBlack = userPreferences.isHighContrastModeEnabled,
                ),
            cache = cache,
        )
    val transition = rememberThemeTransition(built.scheme)
    val themeColors = remember(built, cache) { ThemeColors(built, cache) }

    // A new resolver makes every text lay out again, so it must outlive recompositions.
    val fontFamilyResolver =
        remember(context) {
            val fontHandler = CoroutineExceptionHandler { _, throwable ->
                Log.e("DocucraftTheme", "Error loading font: ${throwable.message}", throwable)
            }
            createFontFamilyResolver(context, fontHandler)
        }

    val displayFont = userPreferences.displayFont.toFontFamily()
    val titleFont = userPreferences.titleFont.toFontFamily()
    val bodyFont = userPreferences.bodyFont.toFontFamily()
    val labelFont = userPreferences.labelFont.toFontFamily()
    val monospaceFont = userPreferences.monospaceFont.toFontFamily() ?: FontFamily.Monospace

    val typography =
        remember(displayFont, titleFont, bodyFont, labelFont) {
            createTypography(
                displayFont = displayFont,
                titleFont = titleFont,
                bodyFont = bodyFont,
                labelFont = labelFont,
            )
        }
    val docucraftTypography = remember(monospaceFont) { DocucraftTypography(monospaceFont) }

    CompositionLocalProvider(
        LocalFontFamilyResolver provides fontFamilyResolver,
        LocalDocucraftTypography provides docucraftTypography,
        LocalThemeColors provides themeColors,
    ) {
        MaterialExpressiveTheme(
            colorScheme = transition.colorScheme,
            motionScheme = transition.motionScheme(motionScheme),
            typography = typography,
            content = content,
        )
    }
}

/**
 * The app's theme around one color, for a screen that is about something the user gave a color to:
 * everything in [content] takes that color, and the rest of the app keeps its own.
 *
 * A theme of its own rather than a change of the app's: only [content] is recomposed for it. A
 * screen whose color was shown before opens in it, and the navigation's own transition takes the
 * app from one to the other; a color seen for the first time is built in the background and arrived
 * at as any change of theme is (see [rememberThemeTransition]).
 *
 * The color is a hue to build a scheme from, not a color to show: it is pulled towards the theme's
 * primary so that it sits beside the user's own colors, and the scheme keeps the theme's style and
 * darkness.
 *
 * @param accent The color, or `null` for none, which leaves the app's theme as it is. It may come
 *   and go while [content] stays.
 */
@Suppress("ModifierRequired")
@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun DocucraftAccentTheme(accent: Color?, content: @Composable () -> Unit) {
    val appScheme = MaterialTheme.colorScheme
    // None under a bare MaterialTheme, as in a preview: there is no source to build from.
    val themeColors = LocalThemeColors.current

    val target =
        if (accent != null && themeColors != null) {
            // Harmonized with the theme the app is heading to, not the step it is at: a change of
            // theme must ask for one new scheme, not one for each step of the way.
            val primary = themeColors.built.scheme.primary
            val seed =
                remember(accent, primary) { Blend.harmonize(accent.toArgb(), primary.toArgb()) }
            rememberColorScheme(
                    source =
                        themeColors.built.source.copy(useWallpaperColors = false, seedColor = seed),
                    cache = themeColors.cache,
                    placeholder = appScheme,
                )
                .scheme
        } else {
            // Where the app is heading as well, not the step it is at: following its steps would
            // start a change of this theme's own at each of them, and arrive after the app has.
            themeColors?.built?.scheme ?: appScheme
        }
    val transition = rememberThemeTransition(target)

    // Expressive, as the app's is, to hand down a motion scheme: what Material's components animate
    // of their own has to keep up with this theme's changes too, not only with the app's.
    MaterialExpressiveTheme(
        colorScheme = transition.colorScheme,
        motionScheme = transition.motionScheme(MaterialTheme.motionScheme),
        shapes = MaterialTheme.shapes,
        typography = MaterialTheme.typography,
        content = content,
    )
}

@Immutable
internal data class ColorSchemeSource(
    val isDark: Boolean,
    val useWallpaperColors: Boolean,
    val seedColor: Int,
    val paletteStyle: PaletteStyleConfig,
    val pureBlack: Boolean,
)

/** A scheme with what it was built from: the two are only ever read together. */
@Immutable internal class BuiltColorScheme(val source: ColorSchemeSource, val scheme: ColorScheme)

/**
 * What a theme nested in the app's needs to build a scheme of its own in keeping with it: the
 * scheme the app is in, or heading to, and what it was built from.
 */
@Immutable internal class ThemeColors(val built: BuiltColorScheme, val cache: ColorSchemeCache)

private val LocalThemeColors = staticCompositionLocalOf<ThemeColors?> { null }

private fun ColorSchemeSource.build(context: Context): ColorScheme =
    if (useWallpaperColors && isDynamicColoringSupported()) {
        if (isDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
    } else {
        dynamicColorScheme(
            seedColor = Color(seedColor),
            isDark = isDark,
            isAmoled = pureBlack,
            specVersion = DocucraftColorSpec,
            style = paletteStyle.toPaletteStyle(),
        )
    }

/**
 * The color scheme for [source], built only when it changes. Generating one takes milliseconds, so
 * each change is built in the background, and the scheme before it stays until it is ready.
 *
 * @param placeholder What to show while the first scheme is built. Without one the first is built
 *   in place, as the app's has to be: its first frame needs it.
 */
@Composable
private fun rememberColorScheme(
    source: ColorSchemeSource,
    cache: ColorSchemeCache,
    placeholder: ColorScheme? = null,
): BuiltColorScheme {
    val context = LocalContext.current
    // A preview is one frame: it shows what the theme arrives at, not what it starts from.
    val waitsForIt = placeholder != null && !LocalInspectionMode.current
    var built by
        remember(cache) {
            val scheme =
                cache[source]
                    ?: placeholder.takeIf { waitsForIt }
                    ?: source.build(context).also { cache[source] = it }
            mutableStateOf(BuiltColorScheme(source, scheme))
        }
    LaunchedEffect(cache, source) {
        val scheme =
            cache[source]
                ?: withContext(Dispatchers.Default) { source.build(context) }
                    .also { cache[source] = it }
        if (built.source != source || built.scheme !== scheme) {
            built = BuiltColorScheme(source, scheme)
        }
    }
    return built
}

/** Only ever touched on the main thread: a scheme is built off it, and kept from it. */
internal class ColorSchemeCache :
    LinkedHashMap<ColorSchemeSource, ColorScheme>(CACHED_SCHEMES, 0.75f, true) {
    override fun removeEldestEntry(
        eldest: MutableMap.MutableEntry<ColorSchemeSource, ColorScheme>
    ) = size > CACHED_SCHEMES
}

/**
 * Light and dark of the current colors and of the previous ones, and as many again for the screens
 * that have a color of their own.
 */
private const val CACHED_SCHEMES = 8

/** Shared by the theme and the palette previews, so a preview shows what the theme applies. */
internal val DocucraftColorSpec = ColorSpec.SpecVersion.SPEC_2025
