/*
 * Copyright (C) 2026  Gabriel Fontán (BobbyESP)
 */
package com.bobbyesp.docucraft.core.presentation.theme

import android.content.Context
import android.util.Log
import androidx.compose.foundation.layout.Box
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.MaterialExpressiveTheme
import androidx.compose.material3.MotionScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFontFamilyResolver
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.font.createFontFamilyResolver
import androidx.compose.ui.unit.sp
import com.bobbyesp.docucraft.core.domain.model.PaletteStyleConfig
import com.bobbyesp.docucraft.core.domain.model.UserPreferences
import com.materialkolor.dynamicColorScheme
import com.materialkolor.dynamiccolor.ColorSpec
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Immutable
data class DocucraftCustomTypography(
    val monospaceCode: TextStyle =
        TextStyle(
            fontFamily = FontFamily.Monospace,
            fontWeight = FontWeight.Normal,
            fontSize = 13.sp,
            lineHeight = 18.sp,
        )
)

val LocalMonospaceFontFamily = staticCompositionLocalOf<FontFamily> { FontFamily.Monospace }
val LocalDocucraftCustomTypography = staticCompositionLocalOf { DocucraftCustomTypography() }

object DocucraftTheme {
    val customTypography: DocucraftCustomTypography
        @Composable get() = LocalDocucraftCustomTypography.current
}

/**
 * The app's theme: Material 3 Expressive, with colors from the wallpaper or generated by
 * MaterialKolor from the user's seed color.
 *
 * Changing any of its inputs takes the whole app to the new colors with one crossfade (see
 * [rememberThemeTransition]); nothing below the theme animates colors for a theme change.
 *
 * @param isDark whether to use the dark scheme; taken from [userPreferences] unless the caller has
 *   already worked it out.
 */
@Suppress("ModifierRequired")
@OptIn(ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun DocucraftTheme(
    userPreferences: UserPreferences = UserPreferences(),
    isDark: Boolean = userPreferences.themeConfig.isDarkTheme(),
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current
    val motionScheme = MotionScheme.expressive()

    val colorScheme =
        rememberColorScheme(
            ColorSchemeSource(
                isDark = isDark,
                useWallpaperColors = userPreferences.useDynamicColoring,
                seedColor = userPreferences.themeSeedColor,
                paletteStyle = userPreferences.paletteStyle,
                pureBlack = userPreferences.isHighContrastModeEnabled,
            )
        )
    val transition = rememberThemeTransition(colorScheme, motionScheme.slowEffectsSpec())

    // A resolver keeps its own cache of loaded fonts. Created again on each recomposition, it made
    // every downloadable font load again and every text in the app lay out again.
    val fontFamilyResolver =
        remember(context) {
            val fontHandler = CoroutineExceptionHandler { _, throwable ->
                Log.e("DocucraftTheme", "Error loading font: ${throwable.message}", throwable)
            }
            createFontFamilyResolver(context, fontHandler)
        }

    val displayFont = userPreferences.displayFont.toFontFamily()
    val titleFont = userPreferences.titleFont.toFontFamily()
    val bodyFont = userPreferences.bodyFont.toFontFamily()
    val labelFont = userPreferences.labelFont.toFontFamily()
    val monospaceFont = userPreferences.monospaceFont.toFontFamily() ?: FontFamily.Monospace

    val typography =
        remember(displayFont, titleFont, bodyFont, labelFont) {
            createTypography(
                displayFont = displayFont,
                titleFont = titleFont,
                bodyFont = bodyFont,
                labelFont = labelFont,
            )
        }
    val customTypography =
        remember(monospaceFont) {
            DocucraftCustomTypography(
                monospaceCode =
                    TextStyle(
                        fontFamily = monospaceFont,
                        fontWeight = FontWeight.Normal,
                        fontSize = 13.sp,
                        lineHeight = 18.sp,
                    )
            )
        }

    CompositionLocalProvider(
        LocalFontFamilyResolver provides fontFamilyResolver,
        LocalMonospaceFontFamily provides monospaceFont,
        LocalDocucraftCustomTypography provides customTypography,
    ) {
        MaterialExpressiveTheme(
            colorScheme = transition.colorScheme,
            motionScheme = transition.motionScheme(motionScheme),
            typography = typography,
        ) {
            Box(modifier = Modifier.themeTransition(transition), propagateMinConstraints = true) {
                content()
            }
        }
    }
}

/** What a color scheme is built from. */
@Immutable
private data class ColorSchemeSource(
    val isDark: Boolean,
    val useWallpaperColors: Boolean,
    val seedColor: Int,
    val paletteStyle: PaletteStyleConfig,
    val pureBlack: Boolean,
)

private fun ColorSchemeSource.build(context: Context): ColorScheme =
    if (useWallpaperColors && isDynamicColoringSupported()) {
        if (isDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
    } else {
        dynamicColorScheme(
            seedColor = Color(seedColor),
            isDark = isDark,
            isAmoled = pureBlack,
            specVersion = ColorSpec.SpecVersion.SPEC_2025,
            style = paletteStyle.toPaletteStyle(),
        )
    }

/**
 * The color scheme for [source], built only when it changes, and away from the main thread.
 *
 * MaterialKolor takes several milliseconds to generate a whole scheme, which the frame that
 * switches the theme cannot spare. Only the first scheme is built in place, because the first frame
 * needs it; each one after is built in the background, and the current one stays until it is ready.
 * The last few are kept, so going back to a previous theme builds nothing.
 */
@Composable
private fun rememberColorScheme(source: ColorSchemeSource): ColorScheme {
    val context = LocalContext.current
    val cache = remember(context) { ColorSchemeCache() }
    var scheme by
        remember(cache) { mutableStateOf(cache.getOrPut(source) { source.build(context) }) }
    LaunchedEffect(cache, source) {
        scheme =
            cache[source]
                ?: withContext(Dispatchers.Default) { source.build(context) }
                    .also { cache[source] = it }
    }
    return scheme
}

/** The schemes built last, the least recently used dropped first. */
private class ColorSchemeCache :
    LinkedHashMap<ColorSchemeSource, ColorScheme>(CACHED_SCHEMES, 0.75f, true) {
    override fun removeEldestEntry(
        eldest: MutableMap.MutableEntry<ColorSchemeSource, ColorScheme>
    ) = size > CACHED_SCHEMES
}

/** Enough for light and dark of the current colors, and of the ones just left. */
private const val CACHED_SCHEMES = 4
